config/routes.rb
QiitaService::Application.routes.draw do

  root to: 'facebook/oauths#welcome'

  namespace :facebook do
    resources :timelines do
      collection do
        post :search
      end
    end

    resources :oauths do
      collection do
        get :welcome
        get :redirect
      end
    end
  end

  resources :tomodachis
end

app/models/facebook.rb
module Facebook
  def self.table_name_prefix
    'facebook_'
  end
end

app/models/facebook/test_users.rb
class Facebook::TestUsers
  class << self
    
    def find_or_create
      test_users.list[0] || test_user
    end
    
    def find_all
      test_users
    end
    
    private
      def test_users
        Koala::Facebook::TestUsers.new(app_id: Facebook::APP_ID.to_s, secret: Facebook::SECRET.to_s)
      end
        
      def test_user
        test_users.create(app_installed?, permissions)
      end
    
      def app_installed?
        true
      end
  end
end

app/models/facebook/timeline.rb
class Facebook::Timeline < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/tomodachi.rb
class Tomodachi < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/facebook/oauths_controller.rb
#-*- coding: utf-8 -*-
class Facebook::OauthsController < ApplicationController

  def welcome

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def redirect
    cookies[:access_token] = Koala::Facebook::OAuth.new(redirect_facebook_oauths_url).get_access_token(params[:code]) if params[:code]
    logger.debug "oauth_log: #{cookies}"
    redirect_to cookies[:access_token] ? facebook_timelines_url : "http://www.facebook.com/"
  end
end

app/controllers/facebook/timelines_controller.rb
class Facebook::TimelinesController < ApplicationController
  include Facebook::TimelinesHelper

  before_filter :parse_facebook_cookies

  def parse_facebook_cookies
    facebook_cookies
  end

  # GET /facebook/timelines
  # GET /facebook/timelines.json
  def index
    unless access_token
      redirect_to controller: 'facebook/oauths', action: 'welcome'
      return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { head :no_content }
    end
  end

  def search
    @friends = graph.get_connections("me", "friends").map do |friend|
      friend
    end
    logger.debug "search_log2: #{@friends}"

    render json: { status: 'success', friends: @friends}
  end

  # GET /facebook/timelines/1
  # GET /facebook/timelines/1.json
  def show
    @facebook_timeline = Facebook::Timeline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @facebook_timeline }
    end
  end

  # GET /facebook/timelines/new
  # GET /facebook/timelines/new.json
  def new
    @facebook_timeline = Facebook::Timeline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @facebook_timeline }
    end
  end

  # GET /facebook/timelines/1/edit
  def edit
    @facebook_timeline = Facebook::Timeline.find(params[:id])
  end

  # POST /facebook/timelines
  # POST /facebook/timelines.json
  def create
    @facebook_timeline = Facebook::Timeline.new(params[:facebook_timeline])

    respond_to do |format|
      if @facebook_timeline.save
        format.html { redirect_to @facebook_timeline, notice: 'Timeline was successfully created.' }
        format.json { render json: @facebook_timeline, status: :created, location: @facebook_timeline }
      else
        format.html { render action: "new" }
        format.json { render json: @facebook_timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facebook/timelines/1
  # PUT /facebook/timelines/1.json
  def update
    @facebook_timeline = Facebook::Timeline.find(params[:id])

    respond_to do |format|
      if @facebook_timeline.update_attributes(params[:facebook_timeline])
        format.html { redirect_to @facebook_timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @facebook_timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebook/timelines/1
  # DELETE /facebook/timelines/1.json
  def destroy
    @facebook_timeline = Facebook::Timeline.find(params[:id])
    @facebook_timeline.destroy

    respond_to do |format|
      format.html { redirect_to facebook_timelines_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tomodachis_controller.rb
class TomodachisController < ApplicationController
  # GET /tomodachis
  # GET /tomodachis.json
  def index
    @tomodachis = Tomodachi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tomodachis }
    end
  end

  # GET /tomodachis/1
  # GET /tomodachis/1.json
  def show
    @tomodachi = Tomodachi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tomodachi }
    end
  end

  # GET /tomodachis/new
  # GET /tomodachis/new.json
  def new
    @tomodachi = Tomodachi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tomodachi }
    end
  end

  # GET /tomodachis/1/edit
  def edit
    @tomodachi = Tomodachi.find(params[:id])
  end

  # POST /tomodachis
  # POST /tomodachis.json
  def create
    @tomodachi = Tomodachi.new(params[:tomodachi])

    respond_to do |format|
      if @tomodachi.save
        format.html { redirect_to @tomodachi, notice: 'Tomodachi was successfully created.' }
        format.json { render json: @tomodachi, status: :created, location: @tomodachi }
      else
        format.html { render action: "new" }
        format.json { render json: @tomodachi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tomodachis/1
  # PUT /tomodachis/1.json
  def update
    @tomodachi = Tomodachi.find(params[:id])

    respond_to do |format|
      if @tomodachi.update_attributes(params[:tomodachi])
        format.html { redirect_to @tomodachi, notice: 'Tomodachi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tomodachi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tomodachis/1
  # DELETE /tomodachis/1.json
  def destroy
    @tomodachi = Tomodachi.find(params[:id])
    @tomodachi.destroy

    respond_to do |format|
      format.html { redirect_to tomodachis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook/timelines_helper.rb
module Facebook::TimelinesHelper

  def oauth
    @oauth ||= Koala::Facebook::OAuth.new
  end

  def facebook_cookies
    @facebook_cookies ||= Facebook::TestUsers.find_or_create
  end

  def access_token
    cookies[:access_token]
    #facebook_cookies["access_token"]
  end

  def graph
    @graph ||= Koala::Facebook::API.new(access_token)
  end

  def permissions
    %w[publish_stream email offline_access read_stream]
  end
end

app/helpers/tomodachis_helper.rb
module TomodachisHelper
end

app/views/facebook/oauths/_footer.html.haml
%footer
  %p &copy; Headwaters co.,ltd. 2013

app/views/facebook/oauths/welcome.html.haml
.container
  .content
    .page-header
      %h1 Welcome to Tomodachi

      = link_to 'Login', Koala::Facebook::OAuth.new.url_for_oauth_code(:callback => redirect_facebook_oauths_url)

  = render 'footer'

app/views/facebook/timelines/_flow_form.html.haml
= form_tag({action: 'search'}, remote: true) do
  .input
    = text_field_tag :search, nil, class:'input-file'
    = submit_tag 'Search Celeb', class:'btn primary'
    = notice

  %br
  %br
    
  #flow
    - @arrows.each do |arrow|
      %div{id:"#{arrow.id}", class:"box", style:"left:#{arrow.left}; top:#{arrow.top};"}
        %a{name:"#{arrow.id}", href:"##{arrow.target}", class:"#{arrow.class}"}
        %a{name:"#{arrow.name}", href:"#{arrow.url}", target: "_blank"}#{arrow.name}

app/views/facebook/timelines/_footer.html.haml
%footer
  %p &copy; Headwaters co.,ltd. 2011

app/views/facebook/timelines/_form.html.haml
= form_for @facebook_timeline do |f|
  -if @facebook_timeline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@facebook_timeline.errors.count, "error")} prohibited this facebook_timeline from being saved:"
      %ul
        - @facebook_timeline.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .actions
      = f.submit 'Save', :class=>"btn primary"
      %button.btn{:type=>"reset"}="Clear"

app/views/facebook/timelines/edit.html.haml
.container
  .content
    .page-header
      %h1 Editing facebook_timeline

    = render 'form'

    = link_to 'Show', @facebook_timeline
    \|
    = link_to 'Back', facebook_timelines_path
    
  = render 'footer'

app/views/facebook/timelines/index.html.haml
.container
  .content
    .page-header
      %h1 Tomodachi List

    = form_tag({action: 'search'}, id: 'search_form', remote: true) do
      = submit_tag '友達を探す', class:'btn-primary'

  = render 'footer'

app/views/facebook/timelines/new.html.haml
.container
  .content
    .page-header
      %h1 New facebook_timeline

    = render 'form'

    = link_to 'Back', facebook_timelines_path
  
  = render 'footer'

app/views/facebook/timelines/show.html.haml
.container
  .content
    .page-header
      %h1 FacebookTimeline Profile

    .modal{:style=>"position: relative; top: auto; left: auto; margin: 0 auto; z-index: 1"}
      .modal-header
        %h3 FacebookTimeline Profile
        %a.close{:href=>"#{facebook_timelines_path}"} X

      .modal-body
        %p#notice
          %b= notice
      

      .modal-footer
        %a.btn.primary{:href=>"#{edit_facebook_timeline_path(@facebook_timeline)}"} Edit
        %a.btn.secondary{:href=>"#{facebook_timelines_path}"} Back
        
  = render 'footer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QiitaService</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tomodachis/_footer.html.haml
%footer
  %p &copy; Headwaters co.,ltd. 2011

app/views/tomodachis/index.html.haml
.container
  .content
    .page-header
      %h1= @profile["name"]
      
    = render 'flow_form'
    
    %table#tablesorter.zebra-striped
      %thead
        %tr
          %th
          %th
          %th
          
      %tbody
        %tr
          %td  Profile
          %td= @profile["name"]
          %td= @profile
          
        - @friends.each do |friend|
          %tr
            %td  Friends
            %td= friend["name"]
            %td= friend
            
        - @likes.each do |like|
          %tr
            %td  Likes
            %td= like
            %td= like
            
        - @feeds.each do |feed|
          %tr
            %td  Feeds
            %td= feed["message"]
            %td= feed
    
        - @results.each do |result|
          %tr
            %td  Results
            %td= result
            %td= result
            
    %br
    = link_to 'New Timeline', new_facebook_timeline_path
    
  = render 'footer'
  
:coffeescript
  $ ->
    $("table#tablesorter").tablesorter({ sortList: [[0,0]] })
    
    #$(".hoge").square()
    #$(".piyo").circle()
    #$(".hoge").lineTo($(".piyo"))